### PR TITLE
[Feature] Updated Error Bar Request

### PR DESCRIPTION
**Pull request by BrandonReno**
# Description

This PR aims at adding this feature: Error bars in the summary plot method to illustrate standard error of each bin.

# Proposed Changes

I changed the function "Summary_Plot" to take in an bool errorbar parameter that if true will display the error bar and if false will not display errorbar.

# Checklist

Here are some things to check before creating the PR. If you encounter any issues, do let us know :)

- [ X] I have read the [CONTRIBUTING](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#structure-and-code) file.
- [X ] My PR is targetted at the **dev branch** (and not towards the master branch).
- [X ] I ran the [CODE CHECKS](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#run-code-checks) on the files I added or modified and fixed the errors.
image

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
Thanks for the clean-up! I have some general questions / remarks:

- Name of the argument: is `errorbars` (plural) more accurate?
- Rather than a TRUE/FALSE, would it make sense to have something like `None` by default, and then it can be a float that determines the "confidence" (i.e., the size of the error bars), like `errorbar=0.95` for instance?

**Comment by BrandonReno** [comment]
Yes, error bars plural is probably a better naming convention as there are
multiple! I would definitely be willing to fix this!

I do think for a library of this magnitude this is a great idea that just
slipped my mind. I'm sure many people would benefit from being able to use
their own confidence intervals rather than just the default .95. I can make
this change too.

Let me know if both of those sound good and I can go ahead and add
confidence intervals and switch to a plural argument name!

**Comment by BrandonReno** [comment]
Looking more into confidence intervals and standard error and am having a
tough time finding a formula to use. Wondering if you have a valid one that
came to mind when you thought of the idea?

**Comment by BrandonReno** [comment]
> * I would actually remove the argument from all the `hrv` function, and pass it only via kwargs. It is rather uncommon in our API to have "plotting-related arguments" in the functions that are not "plot-focused", for for instance in `hrv()` there are so few arguments that it's weird to have `errorbars` there, as it doesnt affect HRV computation per-se but rather its aesthetic presentation. So what'd I'd do is allow open the **kwargs pipe, and then maybe in the documentation of the `**kwargs` we can have like "Other arguments to be passed to other functions such as `summary_plot()`" with a link to it. Users can understand that they can any of the plotting arguments as kwargs, without having the argument in the function definition. Does that make sense?

This is a good idea and something I felt would be brought up. I can gladly place it as a kwargs argument. In that case would it be treated as ax is? where I have to do a check in summary plot to see if errorbars is in kwargs?

**Comment by BrandonReno** [comment]
Just to make sure Im understanding, For the pipeline of HRV for instance.  I should add kwargs to "hrv", "_hrv_plot" and "summary_plot" as an argument. From there one will pass errorbars=bool through the kwargs argument on hrv and it will carry down to the summary plot call and be put inside that call? @DominiqueMakowski

**Comment by DominiqueMakowski** [comment]
Regarding the formula, I'm not too sure, but in general you have to multiply the standard error by the PPF, like `~ SE * 1.96...` (for ci = 0.95). They explain it [here](https://stackoverflow.com/questions/15033511/compute-a-confidence-interval-from-sample-data) I think.

Now regarding the API, `summary_plot()` should have an `errorbars` argument. Then, in the hrv functions, the function is called like this: `summary_plot(rri, **kwargs)` and the main hrv functions is defined like this `def hrv_time(peaks, sampling_rate=1000, show=False, **kwargs)`. 

This means that people will be able to run `hrv_time(peaks, errorbars=something)`, this means that the extra argument will be passed down through the kwargs into lower levels, and be used whenever it is defined, such as in summary_plot(). Does that help :) ?

**Comment by BrandonReno** [comment]
Let me know if anything else needs to be done or doesnt make sense!

**Comment by BrandonReno** [comment]
> # [Codecov](https://codecov.io/gh/neuropsychology/NeuroKit/pull/415?src=pr&el=h1) Report
> > Merging [#415](https://codecov.io/gh/neuropsychology/NeuroKit/pull/415?src=pr&el=desc) ([219b4e6](https://github.com/neuropsychology/NeuroKit/commit/219b4e63d9cfa6a4c75110365eb3e3efad6da3d1)) into [dev](https://codecov.io/gh/neuropsychology/NeuroKit/commit/0b43f2444f6ffefd38feec3046704d1961c5e3ab?el=desc) ([0b43f24](https://github.com/neuropsychology/NeuroKit/commit/0b43f2444f6ffefd38feec3046704d1961c5e3ab)) will **decrease** coverage by `0.03%`.
> > The diff coverage is `92.42%`.
> 
> [Impacted file tree graph](https://codecov.io/gh/neuropsychology/NeuroKit/pull/415?src=pr&el=tree)
> 
> ```diff
> @@            Coverage Diff             @@
> ##              dev     #415      +/-   ##
> ==========================================
> - Coverage   85.80%   85.77%   -0.04%     
> ==========================================
>   Files         187      189       +2     
>   Lines        8841     8869      +28     
> ==========================================
> + Hits         7586     7607      +21     
> - Misses       1255     1262       +7     
> ```
> 
> [Impacted Files](https://codecov.io/gh/neuropsychology/NeuroKit/pull/415?src=pr&el=tree)	Coverage Δ	
> [neurokit2/complexity/fractal_correlation.py](https://codecov.io/gh/neuropsychology/NeuroKit/pull/415/diff?src=pr&el=tree#diff-bmV1cm9raXQyL2NvbXBsZXhpdHkvZnJhY3RhbF9jb3JyZWxhdGlvbi5weQ==)	`68.18% <0.00%> (ø)`	
> [neurokit2/events/events_find.py](https://codecov.io/gh/neuropsychology/NeuroKit/pull/415/diff?src=pr&el=tree#diff-bmV1cm9raXQyL2V2ZW50cy9ldmVudHNfZmluZC5weQ==)	`80.95% <ø> (ø)`	
> [neurokit2/microstates/microstates_peaks.py](https://codecov.io/gh/neuropsychology/NeuroKit/pull/415/diff?src=pr&el=tree#diff-bmV1cm9raXQyL21pY3Jvc3RhdGVzL21pY3Jvc3RhdGVzX3BlYWtzLnB5)	`71.42% <0.00%> (ø)`	
> [neurokit2/signal/signal_interpolate.py](https://codecov.io/gh/neuropsychology/NeuroKit/pull/415/diff?src=pr&el=tree#diff-bmV1cm9raXQyL3NpZ25hbC9zaWduYWxfaW50ZXJwb2xhdGUucHk=)	`85.71% <ø> (ø)`	
> [neurokit2/signal/signal_zerocrossings.py](https://codecov.io/gh/neuropsychology/NeuroKit/pull/415/diff?src=pr&el=tree#diff-bmV1cm9raXQyL3NpZ25hbC9zaWduYWxfemVyb2Nyb3NzaW5ncy5weQ==)	`100.00% <ø> (ø)`	
> [neurokit2/stats/mutual_information.py](https://codecov.io/gh/neuropsychology/NeuroKit/pull/415/diff?src=pr&el=tree#diff-bmV1cm9raXQyL3N0YXRzL211dHVhbF9pbmZvcm1hdGlvbi5weQ==)	`77.77% <ø> (ø)`	
> [neurokit2/stats/summary.py](https://codecov.io/gh/neuropsychology/NeuroKit/pull/415/diff?src=pr&el=tree#diff-bmV1cm9raXQyL3N0YXRzL3N1bW1hcnkucHk=)	`91.66% <66.66%> (-8.34%)`	⬇️
> [neurokit2/complexity/fractal_dfa.py](https://codecov.io/gh/neuropsychology/NeuroKit/pull/415/diff?src=pr&el=tree#diff-bmV1cm9raXQyL2NvbXBsZXhpdHkvZnJhY3RhbF9kZmEucHk=)	`90.41% <100.00%> (ø)`	
> [neurokit2/complexity/fractal_mandelbrot.py](https://codecov.io/gh/neuropsychology/NeuroKit/pull/415/diff?src=pr&el=tree#diff-bmV1cm9raXQyL2NvbXBsZXhpdHkvZnJhY3RhbF9tYW5kZWxicm90LnB5)	`98.68% <100.00%> (ø)`	
> [neurokit2/complexity/transition_matrix.py](https://codecov.io/gh/neuropsychology/NeuroKit/pull/415/diff?src=pr&el=tree#diff-bmV1cm9raXQyL2NvbXBsZXhpdHkvdHJhbnNpdGlvbl9tYXRyaXgucHk=)	`68.42% <100.00%> (ø)`	
> ... and [20 more](https://codecov.io/gh/neuropsychology/NeuroKit/pull/415/diff?src=pr&el=tree-more)		
> [Continue to review full report at Codecov](https://codecov.io/gh/neuropsychology/NeuroKit/pull/415?src=pr&el=continue).
> 
> > **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> > `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> > Powered by [Codecov](https://codecov.io/gh/neuropsychology/NeuroKit/pull/415?src=pr&el=footer). Last update [014ecc4...219b4e6](https://codecov.io/gh/neuropsychology/NeuroKit/pull/415?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

Do I need to do anything about this? @DominiqueMakowski

**Comment by DominiqueMakowski** [comment]
@BrandonReno I'm waiting for @Tam-Pham to give it a look before merging :) sorry for the delay

**Comment by Tam-Pham** [comment]
Hi @BrandonReno 

SO sorry for the delay and thank you so much for your PR. It's definitely an excellent feature to have. 

Everything looks alright. The drop in codecov is expected. We will see if it drops below our accepted threshold (should not be). However, if you have some time, it would be great if you can  add in a few tests for the chunk of code that are newly added. The tests can be found in neurokit\tests folder. 

I'm gonna merge this PR anyway. The adding of tests can be done later. Thanks much!

**Pull request merged**
