### PR TITLE
add read_acqknowledge and etc

### PR DESCRIPTION
**Pull request by Tam-Pham**
# Description

added new functions to data 
add bioread into deps

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
@Tam-Pham could you add yourself in https://github.com/neuropsychology/NeuroKit/blob/master/AUTHORS.rst in core team and @hungpham2511 to contributors?

Thanks @hungpham2511 😉

**Comment by hungpham2511** [comment]
@DominiqueMakowski You are welcome! Nice, thanks!

**Comment by DominiqueMakowski** [comment]
Now we'd need to add some tests for the functions, which in turn requires to find a neat and efficient way to store data, both to use it in tests and to have some reproducible documentation. 

In neurokit 1 the data was stored as csv in an example folder (https://github.com/neuropsychology/NeuroKit.py/tree/master/examples/Bio) (used in [the documentation](https://github.com/neuropsychology/NeuroKit.py/blob/master/docs/tutorials/Bio.rst#preparation)) and *also* in the tests folder (https://github.com/neuropsychology/NeuroKit.py/tree/master/tests/data). However, the latter seems to not have been further used in the tests (guess I didn't manage to do that).

@hungpham2511 do you by any chance have an idea of the most efficient way to store data so that it could be used in the tests and documentation, but at the same time that would *not* be shipped with the package (to avoid long downloading times)?

**Comment by hungpham2511** [comment]
@DominiqueMakowski I am sure you can configure the `setup.py` in such a way that tests/data are not included in the built distribution to be pushed to PyPI. To avoid downloading, say during, git pull, probably you can put the data to a separate repository and only download when necessary.

**Comment by DominiqueMakowski** [comment]
Thanks, let's merge this for now, we'll address that later ☺️

**Pull request merged**
