### PR TITLE
Functions to account for more `mne` features

### PR DESCRIPTION
**Pull request by zen-juen**
- [x] Account for `first_samp` attribute in mne channels
`mne` raw objects have an attribute called `first_samp` corresponding to the time lapsed after the system start and before the start of the recording, and so the first event's sample number is always > 0. This is taken into account for in mne functions but not in neurokit yet 

See http://predictablynoisy.com/mne-python/generated/mne.io.RawArray.html

- [x] `epochs_plot()` to work with mne objects

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
@zen-juen could you add a `show=False` argument to eeg_badchannels taht would plot all the channels overlayed together in like thin dark grey and the channels detected as "bad" as red on top of them

**Comment by zen-juen** [comment]
> @zen-juen could you add a `show=False` argument to eeg_badchannels taht would plot all the channels overlayed together in like thin dark grey and the channels detected as "bad" as red on top of them

Figure_1

Currently looks like this

**Comment by DominiqueMakowski** [comment]
Noice

**Comment by zen-juen** [comment]
If several bad channels

Figure_1

**Pull request merged**
