### PR TITLE
[Fix] refactor ecg_findpeaks

### PR DESCRIPTION
**Pull request by danibene**
# Description

This PR aims to refactor `ecg_findpeaks()` following a failing codeclimate check: https://codeclimate.com/github/neuropsychology/NeuroKit/pull/926

*Avoid deeply nested control flow statements.*
```
                    for missed_peak in missed_peaks:
                        if missed_peak - peaks[idx[-2]] > int(0.36 * sampling_rate) and ma[missed_peak] > 0.5 * th:
                            insort(QRS, missed_peak)
                            break
 ```

Severity: Major
Found in [neurokit2/ecg/ecg_findpeaks.py](https://codeclimate.com/github/neuropsychology/NeuroKit/neurokit2/ecg/ecg_findpeaks.py?from_sha=3d004b47&to_sha=0ea8a2bc) - About 45 mins to fix

# Proposed Changes

I changed the `ecg_findpeaks_hamilton()` function so that it is broken up into smaller functions. I also added a regression test for it.

# Checklist

Here are some things to check before creating the PR. If you encounter any issues, do let us know :)

- [x] I have read the [CONTRIBUTING](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#structure-and-code) file.
- [x] My PR is targeted at the **dev branch** (and not towards the master branch).
- [ ] I ran the [CODE CHECKS](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#run-code-checks) on the files I added or modified and fixed the errors.
- [ ] I have added the newly added features to **News.rst** (if applicable)

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
Nice, though if need be we can also just discard that check on codeclimate -  I wonder whether you have access to codeclimate's NK checks if you log in with ur GH account

**Comment by danibene** [comment]
Couldn't find that option - would it make sense to update the config file in the repository?

**Comment by DominiqueMakowski** [comment]
> Couldn't find that option - would it make sense to update the config file in the repository?

Yeah to be fair I think we should drop codeclimate entirely... it was kinda useful years ago but now with all the GH actions not so much

**Comment by DominiqueMakowski** [comment]
can I merge this?

**Pull request merged**
