### PR TITLE
[Feature] R-R intervals and associated timestamps as input to HRV functions

### PR DESCRIPTION
**Pull request by danibene**
# Description

This PR aims at adding the ability to directly pass R-R intervals to the HRV functions. See also https://github.com/neuropsychology/NeuroKit/issues/684

# Proposed Changes

Instead of separately sanitizing the input and converting to R-R intervals, I added a function `_hrv_format_input()` that can accept a dictionary with the keys `RRI` and `RRI_Time` and always returns the same format (either peaks or intervals depending on the HRV function) regardless of whether peaks or intervals are passed.

# Checklist

Here are some things to check before creating the PR. If you encounter any issues, do let us know :)

- [x] I have read the [CONTRIBUTING](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#structure-and-code) file.
- [x] My PR is targetted at the **dev branch** (and not towards the master branch).
- [x] I ran the [CODE CHECKS](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#run-code-checks) on the files I added or modified and fixed the errors.
- [ ] I have added the newly added features to **News.rst** (if applicable)

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
image

I think the docstrings of intervals_to_peaks failed 🤔

**Comment by danibene** [comment]
> image
> 
> I think the docstrings of intervals_to_peaks failed 🤔

I think I fixed it now! 

Since there's a bit of repetition in the way the intervals are cleaned across functions (`_hrv_sanitize_rri()`, `intervals_to_peaks()`), thoughts on refactoring such that `intervals` is a separate subpackage containing e.g. `intervals_to_peaks()`, `find_successive_intervals()`, `intervals_sanitize()`, and `intervals_preprocess()`? Or should I just leave as is?

**Comment by DominiqueMakowski** [comment]
mmh a subpackage might be overkill, but we could put all these functions in separate files within the hrv module, since HRV is the one that predominantly deals with intervals?

- intervals_to_peaks()
- find_successive_intervals(): could be renamed `intervals_successive()` for consistency?
- intervals_sanitize()
- intervals_preprocess()

Or perhaps just putting these in separate files in the `misc`

**Comment by DominiqueMakowski** [comment]
What about merging intervals_successive with intervals_sanitize()? Or do you think there would be some usecase for intervals_successive() outside of intervals sanitization?

**Comment by DominiqueMakowski** [comment]
If I understand you use it through `_hrv_format_input` which uses it via sanitize in `_hrv_get_rri()` anyway, so we could make it an internal function and put it in hrv_utils no? 

(my thinking is that if a function is mostly used by us or rather than by users in their analysis, it can be good to make it an internal to prevent [feature creep](https://en.wikipedia.org/wiki/Feature_creep) and avoid bloating the documentation - that's why I was asking for potential other use cases that users my have with this)

**Comment by danibene** [comment]
> If I understand you use it through `_hrv_format_input` which uses it via sanitize in `_hrv_get_rri()` anyway, so we could make it an internal function and put it in hrv_utils no?
> 
> (my thinking is that if a function is mostly used by us or rather than by users in their analysis, it can be good to make it an internal to prevent [feature creep](https://en.wikipedia.org/wiki/Feature_creep) and avoid bloating the documentation - that's why I was asking for potential other use cases that users my have with this)

Yes, but I also plan to use `intervals_successive()` within the `hrv_time()` and `hrv_nonlinear()` functions in the PR addressing https://github.com/neuropsychology/NeuroKit/issues/541 :

My current implementation is here: https://github.com/danibene/NeuroKit/blob/feature/adjust_for_missing_intervals/neurokit2/hrv/hrv_time.py#L168-L173

I can still make it an internal function though - should I move it to `_intervals_successive()` in `hrv_utils`?

**Comment by DominiqueMakowski** [comment]
okay cool

> I can still make it an internal function though - should I move it to _intervals_successive() in hrv_utils?

let's do that for now (we can leave all the examples and descriptions), and down the road we can always make it user-facing if need be

**Pull request merged**
