### PR TITLE
[Fix] invalid indices in ecg_delineate

### PR DESCRIPTION
**Pull request by danibene**
# Description

This prevents indices larger than the ECG signal indices from being returned by `ecg_delineate()`. See https://github.com/neuropsychology/NeuroKit/issues/772

# Proposed Changes

I changed `ecg_delineate()` so that regardless of which delineation method is used, the output is postprocessed such that any indices that are larger than the ECG signal indices are removed (originally this postprocessing was only done in `_ecg_delineator_peak()`.

I also changed `ecg_segment()` so that the final heartbeat segment only contains points from the original ECG signal (not zeros appended at the end), since that caused invalid indices to be detected within `ecg_delineate()`. But I can revert this change or make it an optional argument, as invalid indices will be removed in `ecg_delineate()` anyway.

# Checklist

Here are some things to check before creating the PR. If you encounter any issues, do let us know :)

- [x] I have read the [CONTRIBUTING](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#structure-and-code) file.
- [x] My PR is targetted at the **dev branch** (and not towards the master branch).

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
Thanks a lot Dani! seems like there is an error in the execution fo this notebook: docs\examples\bio_custom\bio_custom.ipynb I'm not sure it's related to that particular PR but just in case could you try tu run it manually to make sure it's unrelated?

**Comment by DominiqueMakowski** [comment]
Maybe it creates a problem in the plot of the segments?

**Comment by danibene** [comment]
> Thanks a lot Dani! seems like there is an error in the execution fo this notebook: docs\examples\bio_custom\bio_custom.ipynb I'm not sure it's related to that particular PR but just in case could you try tu run it manually to make sure it's unrelated?

How do you usually run the notebook to test a specific version of NeuroKit?

I added this cell at the top of the notebook (using the `fix/ecg_segment_extra_samples` branch) and it ran fine:

```
import pathlib
import sys

package_dir = pathlib.Path().resolve().parent.parent.parent # where NeuroKit folder is located
sys.path.append(str(package_dir))
```

**Comment by DominiqueMakowski** [comment]
> to test a specific version of NeuroKit?

Actually that's a good question to which I didn't had answer.  Till now I pip uninstalled and installed the target version... 

the workflow error is unrelated to this PR is it?

**Comment by DominiqueMakowski** [comment]
I just re-run and all is in order.

> so that the final heartbeat segment only contains points from the original ECG signal (not zeros appended at the end

I am not sure about this, I like the idea of returning same-length epochs. Maybe we should pad with nan instead?

**Pull request merged**
