### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
@Tam-Pham ok we're back with a working autodoc, there were some modules that we needed to mock (I don't remember why we removed them I think it was at the time when the docs were failing)

**Comment by DominiqueMakowski** [comment]
Alright we can check briefly everything again, and then merge 💪

**Comment by JanCBrammer** [comment]
#172 should fix the failing test

**Comment by DominiqueMakowski** [comment]
interesting, it seems like it fails without failing on 3.6 @Tam-Pham any ideas?

**Comment by DominiqueMakowski** [comment]
okay it got fixed when rerun, I guess travis works in mysterious ways 🤷‍♂

**Pull request merged**
