### PR TITLE
[feature] PPG process pipeline

### PR DESCRIPTION
**Pull request by DominiqueMakowski**
- [x] ppg_process
- [x] ppg_plot (calling the expert @zen-juen)

### CODE REVIEW

**Comment by zen-juen** [comment]
```
    # Simulate data
    ppg = nk.ppg_simulate(duration=10, sampling_rate=1000, heart_rate=70)
    
    # Process signal
    signals, info = nk.ppg_process(ppg, sampling_rate=1000)
    
    # Plot
    nk.ppg_plot(signals) #doctest: +ELLIPSIS
```

Figure_1

@DominiqueMakowski lookin abit liddissss 😄

**Comment by zen-juen** [comment]
Shall we add in readme too?

**Comment by DominiqueMakowski** [comment]
yeah

**Comment by DominiqueMakowski** [comment]
we mege?

**Pull request merged**
