### PR TITLE
[Fix] respiration sampling rate issue

### PR DESCRIPTION
**Pull request by minsooyeo**
change several constant sampling rate to dynamic value

# Description

_below is tutorial of 'neurokit2.rsp.rsp_rrv'_ : link --> https://neurokit2.readthedocs.io/en/latest/functions.html#neurokit2.rsp.rsp_rrv

```python
>>> import neurokit2 as nk
>>>
>>> rsp = nk.rsp_simulate(duration=90, respiratory_rate=15)
>>> rsp, info = nk.rsp_process(rsp)
>>> rrv = nk.rsp_rrv(rsp, show=True) 
```

but, if i want to process a signal with 32 sampling hz

```python
>>> import neurokit2 as nk
>>> from scipy import signal
>>> rsp = nk.rsp_simulate(duration=90, respiratory_rate=15)
>>> rsp = signal.resample(rsp, int((len(rsp) / 1000) * 32))
>>> rsp, info = nk.rsp_process(rsp, sampling_rate=32)
>>> rrv = nk.rsp_rrv(rsp, show=True, sampling_rate=32) 
```

these result are dismatch and i could see a warning 

**Neurokit warning: signal_psd(): The duration of recording is too short to support a sufficiently long window for high frequency resolution. Consider using a longer recording or increasing the `min_frequency**

it should be consider promptly

# Proposed Changes
write down sampling rate each code

# Checklist

Here are some things to check before creating the PR. If you encounter any issues, do let us know :)

- [x] I have read the [CONTRIBUTING](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#structure-and-code) file.
- [ ] My PR is targetted at the **dev branch** (and not towards the master branch).
- [x] I ran the [CODE CHECKS](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#run-code-checks) on the files I added or modified and fixed the errors.

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
@minsooyeo I've rebased your PR so that it goes to the dev branch. Next time, make sure you work from the dev branch ☺️

**Comment by minsooyeo** [comment]
> @minsooyeo I've rebased your PR so that it goes to the dev branch. Next time, make sure you work from the dev branch ☺️

okay i will ☺️

**Comment by minsooyeo** [comment]
> @minsooyeo Thanks for picking up and fixing these issues! Do add yourself as [contributor](https://neurokit2.readthedocs.io/en/latest/authors.html#contributors) and then we can merge this PR 😄

okay

**Comment by minsooyeo** [comment]
> @minsooyeo Thanks for picking up and fixing these issues! Do add yourself as [contributor](https://neurokit2.readthedocs.io/en/latest/authors.html#contributors) and then we can merge this PR 😄

i already send a pull request.
 

> @minsooyeo Thanks for picking up and fixing these issues! Do add yourself as [contributor](https://neurokit2.readthedocs.io/en/latest/authors.html#contributors) and then we can merge this PR 😄

how i can add contributor myself ?

**Comment by zen-juen** [comment]
@minsooyeo You can do so by editting the [AUTHORS.rst](https://github.com/neuropsychology/NeuroKit/blob/master/AUTHORS.rst) file in your forked repository :)

**Comment by minsooyeo** [comment]
> @minsooyeo You can do so by editting the [AUTHORS.rst](https://github.com/neuropsychology/NeuroKit/blob/master/AUTHORS.rst) file in your forked repository :)

i got it and will edit it !
thanks you !

**Comment by zen-juen** [comment]
@minsooyeo have you managed to update the authors file and commit the change to this branch? 😄

**Comment by minsooyeo** [comment]
> @minsooyeo have you managed to update the authors file and commit the change to this branch? 😄

actually... 
i cant find my pull up branch on the github desktop

pull request

how can i load this branch ...?

**Comment by DominiqueMakowski** [comment]
🤔 maybe you need to update somehow? it should be there indeed, otherwise you can click on "Branches" and try to find your branch

**Comment by minsooyeo** [comment]
> 🤔 maybe you need to update somehow? it should be there indeed, otherwise you can click on "Branches" and try to find your branch

i could't find this branch on "Branches"

when i made pull request, i change master branch, so i folk this project again for reset

i think this process cause this problem ...

how can i deal it ??

branches

**Comment by DominiqueMakowski** [comment]
@minsooyeo alright, don't bother too much then, we'll add you on our side. Could you tell us what name/affiliation you want to display? Thanks

**Comment by minsooyeo** [comment]
> @minsooyeo alright, don't bother too much then, we'll add you on our side. Could you tell us what name/affiliation you want to display? Thanks

sorry guys
would you mind add information?

* `Minsoo Yeo <https://github.com/minsooyeo>`_ *(Taewoong Medical Co., Ltd., ROK)*

name: Minsoo Yeo
affiliation: Taewoong Medical Co., Ltd., ROK

many thanks !

**Comment by DominiqueMakowski** [comment]
@minsooyeo alright it seems like we don't see either your PR on our github, and it's likely to be because it comes from an "unexisting repository" which likely has to do with your reform. This might also create some issues if we merge this PR.

Best option I see is for you to re-open a clean PR with these changes. Thanks!

**Comment by minsooyeo** [comment]
> also create some issue

okay

i agree re-open clean PR 

i will make PR again !

thanks !

**Pull request closed without merging**
