### PR TITLE
[Fix + Improvement] Faster _ecg_findpeaks_hamilton and bug-fix

### PR DESCRIPTION
**Pull request by purpl3F0x**
# Description

This PR aims to improve performanc of  `_ecg_findpeaks_hamilton` and fix some probable bugs

# Proposed Changes

### Bug Fixes:
1. Changed possible bug popping from `n_pks` if `len(n_pks) > 8`, it should probably be `len(n_pks)`
2. Removed dead code of `i += 1` at the end of the loop

### Improvements:
1. changed loop iteration range to avoid checks inside the loop
2. use `insort` instead of appending& sorting in an already sorted array (tested about x300-500 times faster on arrays of 50 elements)
3. Use deques instead of manually pushing and popping to reduce constantly allocating new memory.

# Checklist

Here are some things to check before creating the PR. If you encounter any issues, do let us know :)

- [x] I have read the [CONTRIBUTING](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#structure-and-code) file.
- [x] My PR is targeted at the **dev branch** (and not towards the master branch).
- [x] I ran the [CODE CHECKS](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#run-code-checks) on the files I added or modified and fixed the errors.
- [ ] I have added the newly added features to **News.rst** (if applicable)

### CODE REVIEW

**Comment by purpl3F0x** [comment]
Not sure about bug fix 1, but the current code doesn't seem logical.

**Comment by danibene** [comment]
Hi @purpl3F0x , thank you for this! Could you explain what kind of "buggy" behavior you saw that motivated fix 1? It would be ideal if you could add a test https://github.com/neuropsychology/NeuroKit/tree/master/tests demonstrating that your fix works

**Comment by purpl3F0x** [comment]
> Collaborator

Hello, the controversial code is pretty small. On this line https://github.com/neuropsychology/NeuroKit/blob/3d004b4777c3e59b288f46b9f0f812ac1e04b5d4/neurokit2/ecg/ecg_findpeaks.py#L372

There is a check for the length of the `n_pks`, but this part of the code is doing append/pop&on `s_pks`. Those 2 buffers behave similarly, and they hold the last 8 recent peaks. They don't have a relation to each other. It is a typo, from the original repo the code was based from. There is a good possibility it works by accident cause at some point both array will top up and have legth of 8 elements.

**Comment by danibene** [comment]
I see, would you mind opening an issue on the original repository then too? I see that someone already opened an issue about the code at the end of the loop you removed https://github.com/berndporr/py-ecg-detectors/issues/23 

Until it's fixed, I think you could just add comments stating that the implementation differs slightly from the original code

**Comment by purpl3F0x** [comment]
> I see, would you mind opening an issue on the original repository then too? I see that someone already opened an issue about the code at the end of the loop you removed [berndporr/py-ecg-detectors#23](https://github.com/berndporr/py-ecg-detectors/issues/23)
> 
> Until it's fixed, I think you could just add comments stating that the implementation differs slightly from the original code

I will also open an issue on the original repo. (https://github.com/berndporr/py-ecg-detectors/issues/24)

If I'm not mistaken the way this "works", now is with `s_pks` having a max length depending on the input signal, until the length of `n_pks` becomes 8. I think that's what called an undefined behavior 😁.

**Comment by purpl3F0x** [comment]
The issue has been confirmed and fixed on the original repo as of https://github.com/berndporr/py-ecg-detectors/commit/f5d949d505eab76e80b25faf976673a63925166f

**Comment by berndporr** [comment]
Thanks guys. I've applied the fix also to my repo. I had to apply it manually from the diff as you have linted your version but should be in syn now again.

**Review by danibene — APPROVED** [review]
This looks good to me, thanks @purpl3F0x & @berndporr !

**Pull request merged**
