### PR TITLE
0.2.2

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Review by DominiqueMakowski — COMMENTED** [review]
👍

**Comment by DominiqueMakowski** [comment]
@danibene few styling issues: https://codeclimate.com/github/neuropsychology/NeuroKit/pull/705 

(I personally use the black autoformat-on-save feature in VScode, it's pretty neat)

**Comment by danibene** [comment]
> Code Climate has analyzed commit [520231a](https://github.com/neuropsychology/NeuroKit/commit/520231a5764bca3a302e68e011ceca4949800182) and detected **1 issue** on this pull request.
> 
> Here's the issue category breakdown:
> Category 	Count
> Complexity 	1
> 
> View more on [Code Climate](https://codeclimate.com/github/neuropsychology/NeuroKit/pull/705).

@DominiqueMakowski I'm guessing this is from https://github.com/neuropsychology/NeuroKit/blob/dev/neurokit2/ecg/ecg_findpeaks.py#L70-L102 ? Do you think `_ecg_findpeaks_findmethod()` should be rewritten to return the detector function only after checking all the possible method names?

**Comment by DominiqueMakowski** [comment]
all green let's meerge

**Pull request merged**
