### PR TITLE
[docs] Rerun all examples

### PR DESCRIPTION
**Pull request by zen-juen**

### CODE REVIEW

**Comment by zen-juen** [comment]
hmm I seem to have an error loading the ecg_delineate example 🤔

**Comment by DominiqueMakowski** [comment]
> hmm I seem to have an error loading the ecg_delineate example 🤔

👋 @Tam-Pham

**Comment by JanCBrammer** [comment]
> 
> 
> hmm I seem to have an error loading the ecg_delineate example 🤔

@zen-juen, is it similar to #310?

**Comment by Tam-Pham** [comment]
> > hmm I seem to have an error loading the ecg_delineate example 🤔
> 
> @zen-juen, is it similar to #310?

@JanCBrammer I think the notebook was corrupted and hence couldn't be opened. 
However @zen-juen do you also have problem with running the notebook?

**Comment by zen-juen** [comment]
@Tam-Pham  The notebook loads nicely now! But yes I have an issue running the entire notebook due to the same error I had before

```
ValueError: max() arg is an empty sequence
```

but this should be some package problem

**Pull request merged**
