### PR TITLE
dev

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
@JohnDoenut should we rename `fixpeaks` to something else? `cleanpeaks` or something?

**Comment by JohnDoenut** [comment]
> 
> 
> @JohnDoenut should we rename `fixpeaks` to something else? `cleanpeaks` or something?

@DominiqueMakowski , I had similar thoughts. Since the method technically doesn't apply to peaks, it could make more sense to call it `cleanibi` or `cleanperiods`. In that case it might also be worth considering to move the logic of the current `fixpeaks` implementation entirely to `ecg_rate`. The latter could then be called with an "autocorrect" flag or something.

**Comment by DominiqueMakowski** [comment]
@JohnDoenut Mmh initially I was about to say that case we could have`*_findpeaks()` become `_peaks()` (only detection, but with a simpler name than *findpeaks*), to remove this not really relevant `fixpeaks()` step, but then it might still relevant for instance for EDA. So, in this case, yeah, I think it makes sense to move it somewhere to _rate as it is rather specific to the rate (ALTHOUGH detecting anomalies in the rate (the RRi) is built on the assumption that the artefact is in the peak location, hence wouldn't it make sense to fix/remove the artefacted peaks for instance for amplitude as well?).  

We could think of either `ecg_fixrate` or `ecg_cleanrate` that could be either an internal to `ecg_rate` or to expose it? Along with a `ecg_rate_plot()` that could plot the fixed and raw rates, as well as the quadrant diagram on the side (i.e., all plots related to rate and its fixing). What do you think about keeping `_fixpeak()` (mainly for API consistency in regards to other type of signals where it might be useful) and the eventual fixrate/cleanrate/rate_clean? 

(which makes me think that if we are to add functions of the form `something_something_plot()`, we might as well break current plots into subparts (e.g., `ecg_amplitude_plot()`, `ecg_clean_plot()`, ...), and then the main `ecg_plot()` would just gather all the subplots and combine them into one. This would allow users to get specific plots more easily if needed. Thoughts?)


On a side note, I enabled the support for jupyer notebooks for readthedocs, meaning that we will be able to include notebooks directly as examples, which will streamline a lot the example creation workflow (currently described in #87)   @Tam-Pham @zen-juen

**Comment by JohnDoenut** [comment]
@DominiqueMakowski , After thinking a bit more about this I am back to wanting to keep `ecg_fixpeaks()` with the following change: the method would correct the R-peak indices directly and return the artifact indices as well as the corrected R-peak indices.
This means that we could remove the entire artifact correction logic from `ecg_rate()`. The reason I haven't done this before is that I assumed that the artifact correction could not be implemented such that it can be applied to the R-peak indices directly and that it would have to be applied to the rate instead. I think I know now how I could apply the artifact correction to the R-peak indices directly.
(removing extra indices, adding missed indices, and placing the remaining indices {ectopic, longshort} halfway beween their preceding and following neighbors).

If we can agree on this implementation I could refactor the affected methods at some point within the next two weeks.

Also, I don't think that consistency in method names (across modalities) needs to be enforced at all costs. There will necessarily be things that are unique to a specific modality and cannot be generalized.

Really nice with the .ipynb support for the documentation btw!

**Comment by DominiqueMakowski** [comment]
GOAL: merge this monster-PR by tomorrow (Singapore time) 😁 

@sangfrois could you check the [docs](https://external-builds.readthedocs.io/html/neurokit2/103/tutorials/understanding.html) and see if it renders as you expect thanks!

**Comment by sangfrois** [comment]
Of course. The docs look good. I'll make the proposed change.

**Pull request merged**
