### PR TITLE
0.1.6

### PR DESCRIPTION
**Pull request by DominiqueMakowski**
- [ ] In `nk.complexity()` add the bullet list with all the indices that it computes (we don't have anywhere a comprehensive and tidy list of all the indices we compute which is a shame)

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
@zen-juen @Tam-Pham could you pliz check if read_bitalino still works and if it's possible to somehow merge or combine elements of the onedevice code into the multiple one? It's strange to have two completely separate logics for reading one device and multiple no?

**Comment by DominiqueMakowski** [comment]
should merge asap @Tam-Pham @zen-juen do you greenlight it?

**Comment by zen-juen** [comment]
> should merge asap @Tam-Pham @zen-juen do you greenlight it?

@DominiqueMakowski so many changes la ^^ is there any specific change we should look through before merging?

**Comment by DominiqueMakowski** [comment]
@zen-juen more like wether the stuff that you started / modified back then is good enough for merge ^^

But well let's merge and hopefully there are more fixes than breaks 😬

**Pull request merged**
