### PR TITLE
[Docs] Fix documentation of various HRV features

### PR DESCRIPTION
**Pull request by danibene**
# Description

~~Modify the `hrv_time()` function such that the documentation for `MedianNN` reflects what is actually computed and implement the previous description of MedianNN: The median of the absolute values of the successive differences between RR intervals.~~
I corrected some errors in the documentation of `hrv_time()`, `hrv_frequency()`, `hrv_nonlinear()`, `entropy_shannon()`, `entropy_multiscale()`, `fractal_correlation()`, and `fractal_dfa()`.

# Proposed Changes

I changed the `hrv_time()` function as follows:
1. Changed documentation of `MedianNN` and `MCVNN`

~~2. Added `MedianSD` (wasn't sure about the name) as a feature: The median of the absolute values of the successive differences between RR intervals.~~
I also made small changes to the documentation of `hrv_frequency()`, `hrv_nonlinear()`, `entropy_shannon()`, `entropy_multiscale()`, `fractal_correlation()`, and `fractal_dfa()`.

# Checklist
- [x] I have read the [CONTRIBUTING](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#structure-and-code) file.
- [x] My PR is targetted at the **dev branch** (and not towards the master branch).
- [] I ran the [CODE CHECKS](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#run-code-checks) on the files I added or modified and fixed the errors.
`astroid.exceptions.TooManyLevelsError: Relative import with too many levels (2) for module 'hrv_time'` I don't think I caused this
- [ ] I have added the newly added features to **News.rst** (if applicable)

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
Is MedianSD described and used in other studies? Wondering why it would be a good addition

**Comment by danibene** [comment]
@DominiqueMakowski 

> Is MedianSD described and used in other studies? Wondering why it would be a good addition

No, not that I know of, but I thought it might have been intentionally described since it seems to me like a good robust alternative for RMSSD. I can revert that change though such that only the description of MedianNN is corrected, if you'd prefer

**Comment by DominiqueMakowski** [comment]
Yeah let's do that. I mean I agree that this index could be a good index, but on the other hand there is such a proliferation of HRV indices already (a pet peeve of mine ^^) that adding new ones without a preliminary validation would do more harm than good to the field

**Comment by danibene** [comment]
@DominiqueMakowski 

> Yeah let's do that. I mean I agree that this index could be a good index, but on the other hand there is such a proliferation of HRV indices already (a pet peeve of mine ^^) that adding new ones without a preliminary validation would do more harm than good to the field

That makes a lot of sense! I've now reverted that commit & added a couple other small fixes to mistakes I noticed while looking at the HRV docs.

**Comment by DominiqueMakowski** [comment]
Wow, these minor but super important fixes are awesome 😍 thanks a lot

**Pull request merged**
