### PR TITLE
dev

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
Need to add all the functions to ..autodoc in the API

**Comment by sangfrois** [comment]
Here, I think I managed to keep my changes as I wanted them while still keeping your latest commits. Hope everything cool ! :)

**Comment by Tam-Pham** [comment]
@sangfrois oh man! I must have made a mistake! So sorry you have to go through the trouble digging up the commits 😢 Will be more careful next time.

**Comment by DominiqueMakowski** [comment]
Merging this and will start revising in a fresh PR

**Pull request merged**
