### PR TITLE
Fixed potential bug in hrv_nonlinear.py

### PR DESCRIPTION
**Pull request by richrobe**
# Description

This PR aims at fixing a potential bug in the computation of non-linear HRV features (hrv_nonlinear.py)

According to Brennan et al. 2001 (https://doi.org/10.1109/10.959330, Eq. 12) SD2 is computed as: sqrt(2 * std(RR)^2 - 0.5 * std(SD)),
where RR = RR intervals, SD = successive differences

In the code, SD2 is computed as: sqrt(2 * std(SD)^2 - 0.5 * std(SD))

# Proposed Changes

I changed the `hrv_nonlinear()` function so that SD2 (and SD2/SD1, accordingly) is computed correctly.

# Checklist

Here are some things to check before creating the PR.

- [x] I have read the [CONTRIBUTING](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#structure-and-code) file.
- [x] My PR is targetted at the **dev branch** (and not towards the master branch).
- [x] I ran the [CODE CHECKS](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#run-code-checks) on the files I added or modified and fixed the errors.

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
Wow, nice catch @richrobe thanks! Please feel free to add yourself to the [contributors](https://github.com/neuropsychology/NeuroKit/blob/master/AUTHORS.rst#contributors) before I merge ☺️

**Comment by richrobe** [comment]
Thanks! Done :)

**Comment by DominiqueMakowski** [comment]
did you push? cause I see only one file changed in this PR https://github.com/neuropsychology/NeuroKit/pull/252/files

**Comment by richrobe** [comment]
Did it work now...? Sorry, I think it was the wrong branch before.

**Comment by DominiqueMakowski** [comment]
Got it, thanks again! looking forward to your future contributions!

**Pull request merged**
