### PR TITLE
Error bar branch

### PR DESCRIPTION
**Pull request by BrandonReno**
# Description

This PR adds the error bar feature to HRV summar_plot

# Proposed Changes

I changed the summary_plot, and HRV_Time, HRV calls to all include errbar parameter that is defaulted at False. If user specifies errorbar = true then the histogram will populate the same but will have added error bars on each bin

# Checklist

Here are some things to check before creating the PR. If you encounter any issues, do let us know :)

- [ X] I have read the [CONTRIBUTING](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#structure-and-code) file.
- [X ] My PR is targetted at the **dev branch** (and not towards the master branch).
- [ X] I ran the [CODE CHECKS](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#run-code-checks) on the files I added or modified and fixed the errors.

### CODE REVIEW

**Comment by BrandonReno** [comment]
The reason this is XXL is because when pushed I had run the command to reformat the entire project.  Having trouble delineating the error but should not be a hard fix. Don't know why the first test failed as the line that failed I did not change

**Comment by BrandonReno** [comment]
I also have never worked open source before so I may have missed some things, would love to work them out though!

**Comment by DominiqueMakowski** [comment]
Hey @BrandonReno thanks a lot for the PR ☺️ 

> I also have never worked open source before so I may have missed some things

No worries everybody has to start!

Indeed, with all the files changed it's a bit hard to review 😕 (also while some of the formatting seems correct, other elements don't match our style: e.g., added periods at the end of docstrings titles, line-length, etc.)

Maybe you could 1) copy the files that you changed somewhere else on your computer; 2) revert all the commits of this PR (if you don't know how let me know I can do it for you); 3) re-add the files that you changed and push it so that we could see clearer :)

Also, could you paste an image of the end-results here? Thanks!

**Comment by BrandonReno** [comment]
I will make sure to do that today! Thanks for your help! Sorry again about
the mess !!

**Comment by BrandonReno** [comment]
> Hey @BrandonReno thanks a lot for the PR ☺️
> 
> > I also have never worked open source before so I may have missed some things
> 
> No worries everybody has to start!
> 
> Indeed, with all the files changed it's a bit hard to review 😕 (also while some of the formatting seems correct, other elements don't match our style: e.g., added periods at the end of docstrings titles, line-length, etc.)
> 
> Maybe you could 1) copy the files that you changed somewhere else on your computer; 2) revert all the commits of this PR (if you don't know how let me know I can do it for you); 3) re-add the files that you changed and push it so that we could see clearer :)
> 
> Also, could you paste an image of the end-results here? Thanks!

image

**Pull request closed without merging**
