### PR TITLE
0.0.37

### LINKED ISSUE #247: Improving the signal_interpolate() API.
While the issue of signal_interpolation() is discussed in #242 and #243, I also noticed that in `_signal_formatpeaks_sanitize()`, the `desired length` for interpolation is set as `len(peaks_signal)`, which would be the length of the entire signal. 
https://github.com/neuropsychology/NeuroKit/blob/a8d2981155b031e88188b126e3120c74730bf792/neurokit2/signal/signal_formatpeaks.py#L71

However, in its use case in `signal_period()`, where `period` is interpolated between `peaks`, shouldn't the `desired_length` be the length between the `first_peak` and `last_peak` instead of the length of the entire signal?

@JanCBrammer @DominiqueMakowski. What do you guys think?

### LINKED ISSUE #255: Initialize EOG submodule for basic EOG preprocessing pipeline
Will be useful to have some basic EOG functions as @DominiqueMakowski suggested previously - have started out with
- `nk.eog_extract()` to extract EOG signals from a mne.io.Raw object - but will probably remove this function and include an argument for eog in `nk.mne_channel_extract()` which we already have in our eeg module
- `nk.eog_clean()` based on Agarwal, M., & Sivakumar, R. (2019, September). Blink: A Fully Automated Unsupervised Algorithm for Eye-Blink Detection in EEG Signals. In 2019 57th Annual Allerton Conference on Communication, Control, and Computing (Allerton) (pp. 1113-1121). IEEE.
 (can include more methods later down the road)
- `nk.eog_process()` to include the raw eog signal, cleaned, blinks markers (1 vs 0), and eye blinks rate. Currently the rate is computed in this process function based on extracting blink events from mne.io.Raw and using `nk.signal_period()`. Will create our own `nk.eog_peaks()` to wrap some MNE functions before updating `nk.eog_process()` to reflect the changes
  - Event recognizer tool: https://github.com/bwrc/eogert (https://core.ac.uk/download/pdf/158976592.pdf)

This should also help with starting the EEG pipeline https://github.com/neuropsychology/NeuroKit/issues/225 😄

### PR DESCRIPTION
**Pull request by DominiqueMakowski**
close #247 close #255

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
@JanCBrammer You can run this:

```
isort myfile.py -l 120  --balanced --multi-line 3 --lines-between-types 1 --lines-after-imports 2 --trailing-comma
black myfile.py --line-length 120
docformatter myfile.py --wrap-summaries 120 --wrap-descriptions 113 --blank  --make-summary-multi-line --in-place
```

It might save you some troubles ^^ we are looking at having black and isort and docformatter automatically making PRs to fix each commit, but we have to see if it's not too intrusive

**Comment by JanCBrammer** [comment]
> we are looking at having black and isort and docformatter automatically making PRs to fix each commit

@DominiqueMakowski, that would be awesome. And maybe it would make contributing feel less cumbersome for new people.

**Comment by DominiqueMakowski** [comment]
@JanCBrammer @Tam-Pham @zen-juen ok to merge?

**Comment by JanCBrammer** [comment]
👍

**Comment by Tam-Pham** [comment]
👿

**Comment by Tam-Pham** [comment]
@DominiqueMakowski let's merge

**Pull request merged**
