### PR TITLE
0.2.5

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Comment by danibene** [comment]
It seems the tests are failing because the newest version of sklearn wants us to use `valid_metrics()` instead of `valid_metrics`:

https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KDTree.html

**Comment by DominiqueMakowski** [comment]
I suspect that some dependency creates some problems downstream, because tests are failing despite not having changed anything critical afaik

**Comment by DominiqueMakowski** [comment]
Should we merge?

**Comment by danibene** [comment]
> Should we merge?

Yes! I'll let you do the honors here

**Comment by DominiqueMakowski** [comment]
Of course I had forgotten unpushed changes 😶‍🌫️ 
I added `signal_fillmissing()` to start adding a bit of control / flexibility in some cleaning pipelines (touched only PPG for now)

**Comment by danibene** [comment]
@DominiqueMakowski I think we can merge with this! 

To be considered maybe in a future version if we want to rather adopt the peak detection functions to exclude periods of missing data, especially if these periods are longer (so that we don't have a distorted heart rate due to filled in data)

**Pull request merged**
