### PR TITLE
[Improvement] Faster _ecg_findpeaks_elgendi

### PR DESCRIPTION
**Pull request by purpl3F0x**
# Description

Optimize _ecg_findpeaks_elgendi in those areas of the code:
1. `blocks` could be just a bool array
2. Detection of start/end of block by only comparing `prev` vs `cur` (`blocks[i-1]`, `blocks[i]`) value. (about 2x faster) (even better when combined with *"1"*)
3. Use `enumerate(zip(...))` for iterating the array, (gives a small performance -but measurable- improvement)
4. Move some thresholds outisde of the loop, not to get calculated at each iteration

# Checklist

Here are some things to check before creating the PR. If you encounter any issues, do let us know :)

- [x] I have read the [CONTRIBUTING](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#structure-and-code) file.
- [x] My PR is targeted at the **dev branch** (and not towards the master branch).
- [x] I ran the [CODE CHECKS](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#run-code-checks) on the files I added or modified and fixed the errors.
- [ ] I have added the newly added features to **News.rst** (if applicable)

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
For some reason it fails the tests

**Comment by purpl3F0x** [comment]
It seems to be passing this time., worried-I did some copy-pasta typo on the variables. but seems ok now 🤷

**Comment by DominiqueMakowski** [comment]
Out of curiosity, do you have a benchmark do show how much time we shave wit the version?

**Comment by purpl3F0x** [comment]
> Out of curiosity, do you have a benchmark do show how much time we shave wit the version?

I did some measurments, mainly on individual parts of the code. Don't have the excact numbers in hand, but:
- the comparison optimization is 2x faster on average&worst case since it gets narrowed down from up to 4 to up to 2.
- On using the bool array, without taking into account the reduced memory footprint + not traversing the loop for finding it's max value (why was this needed??)
image

**Comment by DominiqueMakowski** [comment]
Nice job, thanks!

**Pull request merged**
