### PR TITLE
[API] API of signal_period() and signal_rate()

### PR DESCRIPTION
**Pull request by Tam-Pham**
## To continue discuss and finalize our discussion in #247 

We last agreed to **remove** `peaks` argument and **add** `signal` to `signal_period()` and `signal_rate()`.  And within these functions, `peaks` will be identified with `signal_findpeaks()`. 

However, on 2nd thought, I think `signal_findpeaks()` is a very general function. We have more specialized functions, for instance `ecg_peaks()` for different signal. For instance, here:

https://github.com/neuropsychology/NeuroKit/blob/65147605838947aa609e8116bfd5e80a60d5f419/neurokit2/ecg/ecg_process.py#L98

And hence, completely removing the `peaks` argument might not be the best solution imo (unless we want to specify the type of find_peaks() functions in `signal_period()` 🤔).

I made the changes in this PR to add signal (without removing peak) in `signal_period()` and `signal_rate()`. However, a problem I encountered is with `rsp_rrv()`

https://github.com/neuropsychology/NeuroKit/blob/65147605838947aa609e8116bfd5e80a60d5f419/neurokit2/rsp/rsp_rrv.py#L219

I don't know what to pass into this function as `signal` 😅 

What do u guys think? @JanCBrammer @DominiqueMakowski

### CODE REVIEW

**Comment by JanCBrammer** [comment]
> I think `signal_findpeaks()` is a very general function. We have more specialized functions, for instance `ecg_peaks()` for different signal.

Looks like I haven't thought this through :grin:

> completely removing the `peaks` argument might not be the best solution

@Tam-Pham, agreed! Maybe it's best to stick to our original idea: Only have the `peaks` argument and by default not interpolate between `peaks`. Interpolation must be requested by setting `desired_length`. After all, it's only about making sure that nothing breaks downstream when `desired_length` is left at the default `None`.

It feels like having both arguments, `signal` and `peaks` could be confusing and also makes the implementation unnceccesarily convoluted (since, as you already pointed out, it would require passing the signal modality to a function that is supposed to be modality-agnostic).

**Comment by Tam-Pham** [comment]
@JanCBrammer yes, I agree that having both `signal` and `peaks` argument is too clunky (signal is there just for its length!) 
> Maybe it's best to stick to our original idea: Only have the peaks argument and by default not interpolate between peaks. Interpolation must be requested by setting desired_length. After all, it's only about making sure that nothing breaks downstream when desired_length is left at the default None.

Okay! Let's stick to our original idea 😁

**Comment by JanCBrammer** [comment]
@Tam-Pham, if you have no further additions I think we can merge.

**Comment by Tam-Pham** [comment]
Superb! @JanCBrammer 
Let's merge this 😁

**Pull request merged**
