### PR TITLE
dev

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Comment by hungpham2511** [comment]
Hi guys, it looks like the tests are failing, and actually the code is building correctly. I need to place 
```
import scipy.ndimage
import scipy.signal
```
to `ecg_simulate.py` but there is still a failing case:
```
tests/tests_ecg.py F                                                                                                                                                                                         [ 16%]
tests/tests_events.py ...                                                                                                                                                                                    [ 66%]
tests/tests_signal.py ..                                                                                                                                                                                     [100%]

===================================================================================================== FAILURES =====================================================================================================
________________________________________________________________________________________________ test_ecg_simulate _________________________________________________________________________________________________

    def test_ecg_simulate():

        ecg1 = nk.ecg_simulate(duration=5, length=1000)
        assert len(ecg1) == 1000

        ecg2 = nk.ecg_simulate(duration=5, length=1000, bpm=120)
>       assert np.std(ecg1) < np.std(ecg2)
E       assert 0.1759713267085519 < 0.17588644935948536
E        +  where 0.1759713267085519 = <function std at 0x7fef06b96378>(array([ 3.85278574e-02,  4.29004916e-02,  5.55217862e-02,  7.56468291e-02,\n        1.02530708e-01,  1.35428512e-01,  1...2307e-02,  1.39539100e-02,  9.36050930e-03,\n        4.42242822e-03, -7.59338098e-05, -3.35017730e-03, -4.61590280e-03]))
E        +    where <function std at 0x7fef06b96378> = np.std
E        +  and   0.17588644935948536 = <function std at 0x7fef06b96378>(array([ 1.94856860e-02,  3.57545921e-02,  8.17290222e-02,  1.53160543e-01,\n        2.45509984e-01,  3.50760782e-01,  4...3670e-04, -3.57045762e-03, -5.55796203e-03,\n       -7.26664291e-03, -9.16385575e-03, -1.07376545e-02, -1.13942149e-02]))
E        +    where <function std at 0x7fef06b96378> = np.std

tests/tests_ecg.py:16: AssertionError

```

**Comment by DominiqueMakowski** [comment]
Nice catch! (and thanks again 😅) Can we comment out this test for now to see if it works? I'll address that later

**Comment by hungpham2511** [comment]
You are welcome! That should work. I will try that later.

**Comment by DominiqueMakowski** [comment]
Seems matplotlib is failing on 3.8, which is a known issue:

https://github.com/matplotlib/matplotlib/issues/15041

It says here:

> This is what helped me
    python -m pip install -U matplotlib==3.2.0rc1

@hungpham2511 do you think it's better to specify this version somewhere in the documentation or just not to test on 3.8 yet?

**Comment by hungpham2511** [comment]
@DominiqueMakowski if you check the CI results for the other versions, you will see the test failing there, but for some reason these are still considered pass :)

In my opinion, if matplotlib is non-essential we should remove it from setup.py, but keep it in requirements.txt. This help to minimize dependency issues which can be quite annoying (like this one).

**Pull request merged**
