### PR TITLE
[Feature] Add Harrison RVT

### PR DESCRIPTION
**Pull request by jannik-gut**
# Description
This PR aims to add [Harrison's method](https://www.sciencedirect.com/science/article/pii/S1053811921000641) of Respiratory Volume per Time (RVT) as discussed in #495 . And mostly follows the [official Matlab implementation](https://github.com/translationalneuromodeling/tapas/blob/master/PhysIO/code/model/tapas_physio_rvt_hilbert.m).

The only conscious difference is that I added an additional check for small breaths/noise, which led to problems and now skips and issues a warning.
- neurokit2/rsp/rsp_rvt.py:136
- neurokit2/rsp/rsp_rvt.py:148

# Proposed Changes
- I added the file neurokit2/rsp/rsp_rvt.py with the adjacent function
- I added the new function to neurokit2/rsp/__init__.py
- Also some tests were created in tests/tests_rsp.py
    - (If there are other ideas for tests, please let me know)
- To see if the method works, there is also a notebook Test_notebook_to_be_removed.ipynb
    - This notebook has to be removed before merging.

# Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#structure-and-code) file.
- [x] My PR is targetted at the **dev branch** (and not towards the master branch).
- [x] I ran the [CODE CHECKS](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#run-code-checks) on the files I added or modified and fixed the errors.
- [ ] I have added the newly added features to **News.rst** (if applicable)

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
Thanks a lot @jannik-gut! the implementation looks very clean, will review it asap :)

**Comment by DominiqueMakowski** [comment]
Feel free to add yourself to the [Contributors list](https://github.com/neuropsychology/NeuroKit/blob/master/AUTHORS.rst) :)

**Comment by jannik-gut** [comment]
Thank you for the improvements and the feedback!
1. I added two sentences roughly paraphrased from the [Harrison paper](https://www.sciencedirect.com/science/article/pii/S1053811921000641#bib0037) chapter 1.2
     - Let me know if I should read more into it.
2. That should work.
3. I gave the simulated rsp signal to the assert statement and not the rvt in the fix.
     - Let's hope the tests now work.
4. I have removed the big notebook. You can remove it from the history by squashing before merging, else I can also look into it.
5. I will add myself to contributors once I know if I can recover my other account. I will add that change to contributors to e.g. a bug fix next week if that is okay with you.

**Comment by rostro36** [comment]
@DominiqueMakowski
I recovered my other account. Sorry for the shenanigans with two accounts and I have added myself to the contributors.

**Comment by DominiqueMakowski** [comment]
No worries, and thanks a lot :)

**Pull request merged**
