### PR TITLE
[Fix] EDA peak detection and sympathetic activity

### PR DESCRIPTION
**Pull request by GanshengT**
# Description

This PR aims at fix the issue mentioned at #778, #780 and #779

# Proposed Changes

if the user chooses to 'posada' to calculate Sympathetic Nervous System Index, EDA signal will be resampled at 400Hz. A low-pass filter is also added according to original paper. `eda_findpeaks()` using methods proposed in nabian2018 is reviewed and improved. Differentiation has been added before smoothing. Skin conductance response criteria have been revised based on the original paper.

In the eda.find_peaks sub-module, _eda_findpeaks_vanhalem2020 has been revised. The algorithm is changed based on the orginal paper.
` We specified a peak when a consistent increase of 0.5 seconds would follow a consistent decrease of 0.5 seconds.`
However, if eda signals ends before the peak recovers, the offset will not be detected.

# Checklist

Here are some things to check before creating the PR. If you encounter any issues, do let us know :)

- [+ ] I have read the [CONTRIBUTING](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#structure-and-code) file.
- [ +] My PR is targetted at the **dev branch** (and not towards the master branch).
- [ +] I ran the [CODE CHECKS](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#run-code-checks) on the files I added or modified and fixed the errors.
- [+ ] I have added the newly added features to **News.rst** (if applicable)

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
Thanks :) It seems like it throws an error when a short signal is passed. Should we try to adjust nperseg or the overlap so that it doesn't fail in that case? If not,skip when shorter than some minimal length?

```python
import neurokit2 as nk

eda = nk.data('bio_resting_8min_100hz')['EDA']

indexes_posada = nk.eda_sympathetic(eda[0:2000], sampling_rate=100, method='posada', show=True)
```
```
ValueError: noverlap must be less than nperseg.
```

**Comment by GanshengT** [comment]
> Thanks :) It seems like it throws an error when a short signal is passed. Should we try to adjust nperseg or the overlap so that it doesn't fail in that case? If not,skip when shorter than some minimal length?
> 
> ```python
> import neurokit2 as nk
> 
> eda = nk.data('bio_resting_8min_100hz')['EDA']
> 
> indexes_posada = nk.eda_sympathetic(eda[0:2000], sampling_rate=100, method='posada', show=True)
> ```
> 
>  ```
> ValueError: noverlap must be less than nperseg.
> ```

The algorithm is proposed for data that is more than 60 seconds. I suggest that we skip or maybe return a warning "Input signal should be more than 60 seconds when using posada method".

**Comment by DominiqueMakowski** [comment]
Seems like there is bug in the nabian method that makes the docstring examples fail:

```
File D:\a\NeuroKit\NeuroKit\neurokit2\eda\eda_findpeaks.py:373, in _eda_findpeaks_nabian2018(eda_phasic)
    368 window = eda_phasic[i:j]
    369 # The amplitude of the SCR is obtained by finding the maximum value
    370 # between these two zero-crossings and calculating the difference
    371 # between the initial zero crossing and the maximum value.
    372 # amplitude defined in neurokit2
--> 373 amp = np.max(window)
    375 # Detected SCRs with amplitudes less than 10% of max SCR amplitude will be eliminated
    376 # we append the first SCR
    377 if len(amps_list) == 0:
    378     # be careful, if two peaks have the same amplitude, np.where will return a list

File <__array_function__ internals>:200, in amax(*args, **kwargs)

File C:\hostedtoolcache\windows\Python\3.10.10\x64\lib\site-packages\numpy\core\fromnumeric.py:2820, in amax(a, axis, out, keepdims, initial, where)
   2703 @array_function_dispatch(_amax_dispatcher)
   2704 def amax(a, axis=None, out=None, keepdims=np._NoValue, initial=np._NoValue,
   2705          where=np._NoValue):
   2706     """
   2707     Return the maximum of an array or maximum along an axis.
   2708 
   (...)
   2818     5
   2819     """
-> 2820     return _wrapreduction(a, np.maximum, 'max', axis, None, out,
   2821                           keepdims=keepdims, initial=initial, where=where)

File C:\hostedtoolcache\windows\Python\3.10.10\x64\lib\site-packages\numpy\core\fromnumeric.py:86, in _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs)
     83         else:
     84             return reduction(axis=axis, out=out, **passkwargs)
---> 86 return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

ValueError: zero-size array to reduction operation maximum which has no identity
```

**Comment by GanshengT** [comment]
Could you tell me which example is failed?
I tried to run the following lines, no error is reported
eda_signal = nk.eda_simulate(duration=30, scr_number=5, drift=0.1, noise=0)
eda_cleaned = nk.eda_clean(eda_signal)
eda = nk.eda_phasic(eda_cleaned)
eda_phasic = eda["EDA_Phasic"].values
nabian2018 = nk.eda_findpeaks(eda_phasic, method="nabian2018")

**Comment by DominiqueMakowski** [comment]
Changing max to nanmax seemed to have fixed the issue 🤷‍♂️ 

I've also taken the liberty of adding you as a contributor, do let me know if it's okay

**Comment by DominiqueMakowski** [comment]
Actually this still does fail:

```python
      import neurokit2 as nk

      # Get phasic component
      eda_signal = nk.eda_simulate(duration=30, scr_number=5, drift=0.1, noise=0, sampling_rate=100)
      eda_cleaned = nk.eda_clean(eda_signal, sampling_rate=100)
      eda = nk.eda_phasic(eda_cleaned, sampling_rate=100)
      eda_phasic = eda["EDA_Phasic"].values
      _, nabian2018 = nk.eda_peaks(eda_phasic, sampling_rate=100, method="nabian2018")
```

Reason is that the windows are empty (`[]`), not sure how to best fix it

**Comment by GanshengT** [comment]
The problem happens because a negative crossing happens before the first positive crossing. In this case, delete the first negative crossing would work.

**Comment by DominiqueMakowski** [comment]
Could you add that or show me how to add?

**Comment by DominiqueMakowski** [comment]
All good it seems, let me know if it's good to merge :)

**Comment by GanshengT** [comment]
I agree to merge.

**Comment by DominiqueMakowski** [comment]
Thanks a lot for diving into these functions, much appreciated

**Pull request merged**
