### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Tam-Pham**
add sampling rate to output of read_acqknowledge

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
before working on adding the final  resampling function to neurokit, let's add the notebook containing the two functions in a folder named "scripts" at the root of the package (https://github.com/neuropsychology/NeuroKit)

**Comment by Tam-Pham** [comment]
ok. I just add the file to the folder scripts in dev branch

**Comment by DominiqueMakowski** [comment]
The checks started to fail since [this](https://github.com/neuropsychology/NeuroKit/pull/12/commits/a460c2109c7064e50197f22cd30567cccc079721) commit, I think it is because of matplotlib, remove all calls to matplotlib ^^

**Comment by DominiqueMakowski** [comment]
good job ☺️

**Pull request merged**
